-- MODULE  DML108  

-- SQL Test Suite, V6.0, Interactive SQL, dml108.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER            

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:0617 DATETIME with predicates, set fns (static)!

   CREATE TABLE TEMPS (
  ENTERED  TIMESTAMP,
  START    DATE,
  APPT     INTERVAL DAY,
  HOUR_IN  TIME,
  HOUR_OUT TIME,
  LUNCH    INTERVAL HOUR TO MINUTE);
-- PASS:0617 If table is created?

   COMMIT WORK;

   CREATE VIEW SUBQ1 AS
  SELECT MIN (HOUR_IN) AS TOO_EARLY,
  MAX (ALL START) AS LATEST,
  AVG (LUNCH) AS AVGLUNCH,
  AVG (DISTINCT LUNCH) AS D_AVGLUNCH,
  SUM (APPT) AS SUMAPPT
  FROM TEMPS;
-- PASS:0617 If view is created?

   COMMIT WORK;

   INSERT INTO TEMPS VALUES (
  TIMESTAMP '1993-11-10 12:25:14',
  DATE '1993-11-12',
  INTERVAL '4' DAY,
  TIME '08:30:00',
  TIME '16:30:00',
  INTERVAL '1:00' HOUR TO MINUTE);
-- PASS:0617 If 1 row is inserted?

   INSERT INTO TEMPS VALUES (
  TIMESTAMP '1993-11-10 13:15:14',
  DATE '1993-11-15',
  INTERVAL '5' DAY,
  TIME '08:30:00',
  TIME '17:30:00',
  INTERVAL '0:30' HOUR TO MINUTE);
-- PASS:0617 If 1 row is inserted?

   INSERT INTO TEMPS VALUES (
  TIMESTAMP '1993-11-17 09:56:48',
  DATE '1994-11-18',
  INTERVAL '3' DAY,
  TIME '09:00:00',
  TIME '17:00:00',
  INTERVAL '1:00' HOUR TO MINUTE);
-- PASS:0617 If 1 row is inserted?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  LUNCH < INTERVAL '1:00' HOUR TO MINUTE;
-- PASS:0617 If count = 1?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  LUNCH <= INTERVAL '1:00' HOUR TO MINUTE;
-- PASS:0617 If count = 3?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  START <> DATE '1993-11-15' AND
  START <> DATE '1993-11-12';
-- PASS:0617 If count = 1?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  START = DATE '1993-11-15' OR
  START = DATE '1993-11-12';
-- PASS:0617 If count = 2?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  HOUR_OUT > TIME '17:00:00';
-- PASS:0617 If count = 1?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  HOUR_OUT >= TIME '17:00:00';
-- PASS:0617 If count = 2?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  ENTERED BETWEEN TIMESTAMP '1993-11-10 00:00:00' AND
                  TIMESTAMP '1993-11-10 23:59:59';
-- PASS:0617 If count = 2?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  HOUR_OUT IN
  (SELECT HOUR_IN + INTERVAL '8' HOUR FROM TEMPS);
-- PASS:0617 If count = 2?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  (START, APPT) OVERLAPS
  (DATE '1993-11-14', INTERVAL '2' DAY);
-- PASS:0617 If count = 2?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  HOUR_OUT = ANY
  (SELECT HOUR_IN + INTERVAL '8' HOUR FROM TEMPS);
-- PASS:0617 If count = 2?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  EXTRACT (YEAR FROM ENTERED) <> SOME
  (SELECT EXTRACT (YEAR FROM START)
  FROM TEMPS);
-- PASS:0617 If count = 3?

   SELECT COUNT(*)
  FROM TEMPS WHERE
  EXTRACT (YEAR FROM START) <> ALL
  (SELECT EXTRACT (YEAR FROM ENTERED)
   FROM TEMPS);
-- PASS:0617 If count = 1?

   SELECT EXTRACT (HOUR FROM TOO_EARLY)
  * 100 + EXTRACT (MINUTE FROM TOO_EARLY)
  FROM SUBQ1;
-- PASS:0617 If 1 row selected and value is 830?

   SELECT EXTRACT (YEAR FROM LATEST),
  EXTRACT (MONTH FROM LATEST) * 100 +
  EXTRACT (DAY FROM LATEST)
  FROM SUBQ1;
-- PASS:0617 If 1 row selected and values are 1994, 1118?

   SELECT EXTRACT (HOUR FROM AVGLUNCH)
  * 100 + EXTRACT (MINUTE FROM AVGLUNCH)
  FROM SUBQ1;
-- PASS:0617 If 1 row selected and value is 49 or 50?
-- NOTE:0617 50 is better but 49 is acceptable.

   SELECT EXTRACT (HOUR FROM D_AVGLUNCH)
  * 100 + EXTRACT (MINUTE FROM D_AVGLUNCH)
  FROM SUBQ1;
-- PASS:0617 If 1 row selected and value is 45?

   SELECT EXTRACT (DAY FROM SUMAPPT)
  FROM SUBQ1;
-- PASS:0617 If 1 row selected and value is 12?

   SELECT COUNT (DISTINCT LUNCH) FROM TEMPS;
-- PASS:0617 If count = 2?

   ROLLBACK WORK;

   DROP TABLE TEMPS CASCADE;
-- PASS:0617 If table and view are dropped?

   COMMIT WORK;

-- END TEST >>> 0617 <<< END TEST

-- *************************************************////END-OF-MODULE
