-- MODULE  DML130  

-- SQL Test Suite, V6.0, Interactive SQL, dml130.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER            

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:0678 Data type semantics with NULL / NOT NULL!

   CREATE TABLE CH1 (
  CH1A CHARACTER (10) NOT NULL,
  CH1B CHARACTER NOT NULL,
  CH1C CHAR (10) NOT NULL);
-- PASS:0678 If table is created?

   COMMIT WORK;

   CREATE TABLE NUM1 (
  NUM1C1 NUMERIC (3, 2) NOT NULL,
  NUM1C2 NUMERIC (2) NOT NULL,
  NUM1C3 NUMERIC NOT NULL);
-- PASS:0678 If table is created?

   COMMIT WORK;

   INSERT INTO CH1 VALUES ('FOO', '', '0123456789');
-- PASS:0678 If 1 row is inserted?

   SELECT CH1A, CH1B, CH1C
  FROM CH1;
-- PASS:0678 If 1 row selected and CH1A = 'FOO       '?
-- PASS:0678 AND CH1B = ' ' and CH1C = '0123456789'?

-- NOTE:0678 One subtest deleted.

   INSERT INTO CH1 VALUES ('FOO',
  'F', 'LITTLETOOLONG');
-- PASS:0678 If ERROR, string data, right truncation, 0 rows selected?

   DELETE FROM CH1;

   INSERT INTO CH1 VALUES ('FOO',
  'F', 'BLANKS       ');
-- PASS:0678 If 1 row is inserted?

   SELECT CH1A, CH1B, CH1C
  FROM CH1;
-- PASS:0678 If 1 row selected and CH1A = 'FOO       '?
-- PASS:0678 AND CH1B = 'F' and CH1C = 'BLANKS    '?

   INSERT INTO NUM1 VALUES (9.99, -99, 9);
-- PASS:0678 If 1 row is inserted?

   SELECT NUM1C1 * 100, NUM1C2, NUM1C3
  FROM NUM1;
-- PASS:0678 If 1 row selected and values are 999, -99, 9?

   DELETE FROM NUM1;

   INSERT INTO NUM1 VALUES (-10, 0, 0);
-- PASS:0678 If ERROR, string data, numeric value out of range?
-- PASS:0678 AND 0 rows inserted?

   INSERT INTO NUM1 VALUES (0, 100, 0);
-- PASS:0678 If ERROR, string data, numeric value out of range?
-- PASS:0678 AND 0 rows inserted?

   INSERT INTO NUM1 VALUES (0, 0, 0.1);
-- PASS:0678 If 1 row is inserted?

   SELECT NUM1C1 * 100, NUM1C2, NUM1C3
  FROM NUM1;
-- PASS:0678 If 1 row selected and values are 0, 0, 0?

   ROLLBACK WORK;

   DROP TABLE NUM1 CASCADE;

   COMMIT WORK;

   DROP TABLE CH1 CASCADE;

   COMMIT WORK;

-- END TEST >>> 0678 <<< END TEST

-- *********************************************

-- TEST:0679 INFO_SCHEM:  Table data types!

   CREATE TABLE LOTSA_TYPES (
  FLAAG CHAR DEFAULT 'Y', KODE CHAR (5) NOT NULL,
  AMPL REAL DEFAULT 3,
  COORD DOUBLE PRECISION, SWAY FLOAT, REVS INTEGER,
  PITCH SMALLINT, DEGREE NUMERIC (3, 2), RUDDER DECIMAL (2));
-- PASS:0679 If table is created?

   COMMIT WORK;

   SELECT COUNT(*) FROM INFO_SCHEM.TABLES
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND TABLE_TYPE = 'BASE TABLE';
-- PASS:0679 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.VIEWS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES';
-- PASS:0679 If count = 0?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'FLAAG' AND ORDINAL_POSITION = 1
  AND COLUMN_DEF = '''Y''' AND DATA_TYPE = 'CHARACTER'
  AND CHAR_MAX_LENGTH = 1 AND CHAR_OCTET_LENGTH
  > 0 AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0679 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'KODE' AND ORDINAL_POSITION = 2
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'CHARACTER'
  AND CHAR_MAX_LENGTH = 5 AND CHAR_OCTET_LENGTH
  > 3 AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'NO';
-- PASS:0679 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'AMPL' AND ORDINAL_POSITION = 3
  AND COLUMN_DEF IS NOT NULL AND DATA_TYPE = 'REAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC >= 8 AND NUM_PREC_RADIX
  = 2 AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0679 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'COORD' AND ORDINAL_POSITION = 4
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'DOUBLE PRECISION'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC > 8 AND NUM_PREC_RADIX
  = 2 AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0679 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'SWAY' AND ORDINAL_POSITION = 5
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'FLOAT'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC >= 8 AND NUM_PREC_RADIX
  = 2 AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0679 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'REVS' AND ORDINAL_POSITION = 6
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTEGER'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC > 0 AND NUM_SCALE = 0 AND
  (NUM_PREC_RADIX = 2 OR NUM_PREC_RADIX = 10)
  AND DATETIME_PREC IS NULL AND INTERVAL_TYPE IS NULL AND
  INTERVAL_PREC IS NULL AND IS_NULLABLE = 'YES';
-- PASS:0679 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'PITCH' AND ORDINAL_POSITION = 7
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'SMALLINT'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC > 0 AND NUM_SCALE = 0 AND
  (NUM_PREC_RADIX = 2 OR NUM_PREC_RADIX = 10)
  AND DATETIME_PREC IS NULL AND INTERVAL_TYPE IS NULL AND
  INTERVAL_PREC IS NULL AND IS_NULLABLE = 'YES';
-- PASS:0679 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'DEGREE' AND ORDINAL_POSITION = 8
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'NUMERIC'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC = 3 AND NUM_SCALE = 2
  AND NUM_PREC_RADIX = 10
  AND DATETIME_PREC IS NULL AND INTERVAL_TYPE IS NULL AND
  INTERVAL_PREC IS NULL AND IS_NULLABLE = 'YES';
-- PASS:0679 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'RUDDER' AND ORDINAL_POSITION = 9
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'DECIMAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC >= 2 AND NUM_SCALE = 0
  AND NUM_PREC_RADIX = 10
  AND DATETIME_PREC IS NULL AND INTERVAL_TYPE IS NULL AND
  INTERVAL_PREC IS NULL AND IS_NULLABLE = 'YES';
-- PASS:0679 If count = 1?

   ROLLBACK WORK;

   DROP TABLE LOTSA_TYPES CASCADE;

   COMMIT WORK;

-- END TEST >>> 0679 <<< END TEST

-- *********************************************

-- TEST:0680 INFO_SCHEM:  View data types!

   CREATE TABLE LT1 (
  FLAAG CHAR DEFAULT 'Y', KODE CHAR (5) NOT NULL,
  AMPL REAL DEFAULT 3,
  COORD DOUBLE PRECISION, SWAY FLOAT, REVS INTEGER);
-- PASS:0680 If table is created?

   COMMIT WORK;

   CREATE TABLE LT2 (
  PITCH SMALLINT, DEGREE NUMERIC (3, 2), RUDDER DECIMAL (2));
-- PASS:0680 If table is created?

   COMMIT WORK;

   CREATE VIEW LOTSA_TYPES AS
  SELECT * FROM LT1, LT2;
-- PASS:0680 If view is created?

   COMMIT WORK;

   SELECT COUNT(*) FROM INFO_SCHEM.TABLES
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND TABLE_TYPE = 'VIEW';
-- PASS:0680 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.VIEWS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES';
-- PASS:0680 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'FLAAG' AND ORDINAL_POSITION = 1
  AND COLUMN_DEF = '''Y''' AND DATA_TYPE = 'CHARACTER'
  AND CHAR_MAX_LENGTH = 1 AND CHAR_OCTET_LENGTH
  > 0 AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0680 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'KODE' AND ORDINAL_POSITION = 2
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'CHARACTER'
  AND CHAR_MAX_LENGTH = 5 AND CHAR_OCTET_LENGTH
  > 0 AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'NO';
-- PASS:0680 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'AMPL' AND ORDINAL_POSITION = 3
  AND COLUMN_DEF IS NOT NULL AND DATA_TYPE = 'REAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC >= 8 AND NUM_PREC_RADIX
  = 2 AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0680 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'COORD' AND ORDINAL_POSITION = 4
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'DOUBLE PRECISION'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC > 8 AND NUM_PREC_RADIX
  = 2 AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0680 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'SWAY' AND ORDINAL_POSITION = 5
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'FLOAT'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC >= 8 AND NUM_PREC_RADIX
  = 2 AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0680 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'REVS' AND ORDINAL_POSITION = 6
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTEGER'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC > 0 AND NUM_SCALE = 0 AND
  (NUM_PREC_RADIX = 2 OR NUM_PREC_RADIX = 10)
  AND DATETIME_PREC IS NULL AND INTERVAL_TYPE IS NULL AND
  INTERVAL_PREC IS NULL AND IS_NULLABLE = 'YES';
-- PASS:0680 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'PITCH' AND ORDINAL_POSITION = 7
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'SMALLINT'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC > 0 AND NUM_SCALE = 0 AND
  (NUM_PREC_RADIX = 2 OR NUM_PREC_RADIX = 10)
  AND DATETIME_PREC IS NULL AND INTERVAL_TYPE IS NULL AND
  INTERVAL_PREC IS NULL AND IS_NULLABLE = 'YES';
-- PASS:0680 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'DEGREE' AND ORDINAL_POSITION = 8
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'NUMERIC'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC = 3 AND NUM_SCALE = 2
  AND NUM_PREC_RADIX = 10
  AND DATETIME_PREC IS NULL AND INTERVAL_TYPE IS NULL AND
  INTERVAL_PREC IS NULL AND IS_NULLABLE = 'YES';
-- PASS:0680 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_TYPES'
  AND COLUMN_NAME = 'RUDDER' AND ORDINAL_POSITION = 9
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'DECIMAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC >= 2 AND NUM_SCALE = 0
  AND NUM_PREC_RADIX = 10
  AND DATETIME_PREC IS NULL AND INTERVAL_TYPE IS NULL AND
  INTERVAL_PREC IS NULL AND IS_NULLABLE = 'YES';
-- PASS:0680 If count = 1?

   ROLLBACK WORK;

   DROP TABLE LT1 CASCADE;

   COMMIT WORK;

   DROP TABLE LT2 CASCADE;

   COMMIT WORK;

-- END TEST >>> 0680 <<< END TEST

-- *********************************************

-- TEST:0682 INFO_SCHEM:  Datetime data types!

   CREATE TABLE LOTSA_DATETIMES (
  C1 DATE, C2 TIME, C3 TIMESTAMP,
  C4 INTERVAL YEAR, C5 INTERVAL MONTH, C6 INTERVAL DAY,
  C7 INTERVAL HOUR, C8 INTERVAL MINUTE, C9 INTERVAL SECOND,
  C10 INTERVAL YEAR TO MONTH,
  C11 INTERVAL DAY TO HOUR,
  C12 INTERVAL DAY TO MINUTE,
  C13 INTERVAL DAY TO SECOND,
  C14 INTERVAL HOUR TO MINUTE,
  C15 INTERVAL HOUR TO SECOND,
  C16 INTERVAL MINUTE TO SECOND);
-- PASS:0682 If table is created?

   COMMIT WORK;

   SELECT COUNT(*) FROM INFO_SCHEM.TABLES
  WHERE TABLE_SCHEM = 'FLATER'
  AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND TABLE_TYPE = 'BASE TABLE';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C1' AND ORDINAL_POSITION = 1
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'DATE'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS
  NOT NULL AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C2' AND ORDINAL_POSITION = 2
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'TIME'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC = 0
  AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C3' AND ORDINAL_POSITION = 3
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'TIMESTAMP'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC = 6
  AND INTERVAL_TYPE IS NULL AND INTERVAL_PREC IS
  NULL AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C4' AND ORDINAL_POSITION = 4
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS NOT NULL
  AND INTERVAL_TYPE = 'YEAR' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C5' AND ORDINAL_POSITION = 5
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS NOT NULL
  AND INTERVAL_TYPE = 'MONTH' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C6' AND ORDINAL_POSITION = 6
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS NOT NULL
  AND INTERVAL_TYPE = 'DAY' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C7' AND ORDINAL_POSITION = 7
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS NOT NULL
  AND INTERVAL_TYPE = 'HOUR' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C8' AND ORDINAL_POSITION = 8
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS NOT NULL
  AND INTERVAL_TYPE = 'MINUTE' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C9' AND ORDINAL_POSITION = 9
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC = 6
  AND INTERVAL_TYPE = 'SECOND' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C10' AND ORDINAL_POSITION = 10
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS NOT NULL
  AND INTERVAL_TYPE = 'YEAR TO MONTH' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C11' AND ORDINAL_POSITION = 11
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS NOT NULL
  AND INTERVAL_TYPE = 'DAY TO HOUR' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C12' AND ORDINAL_POSITION = 12
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS NOT NULL
  AND INTERVAL_TYPE = 'DAY TO MINUTE' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C13' AND ORDINAL_POSITION = 13
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC = 6
  AND INTERVAL_TYPE = 'DAY TO SECOND' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C14' AND ORDINAL_POSITION = 14
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC IS NOT NULL
  AND INTERVAL_TYPE = 'HOUR TO MINUTE' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C15' AND ORDINAL_POSITION = 15
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC = 6
  AND INTERVAL_TYPE = 'HOUR TO SECOND' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   SELECT COUNT(*) FROM INFO_SCHEM.COLUMNS
  WHERE TABLE_SCHEM = 'FLATER' AND TABLE_NAME = 'LOTSA_DATETIMES'
  AND COLUMN_NAME = 'C16' AND ORDINAL_POSITION = 16
  AND COLUMN_DEF IS NULL AND DATA_TYPE = 'INTERVAL'
  AND CHAR_MAX_LENGTH IS NULL AND CHAR_OCTET_LENGTH
  IS NULL AND NUM_PREC IS NULL AND NUM_PREC_RADIX
  IS NULL AND NUM_SCALE IS NULL AND DATETIME_PREC = 6
  AND INTERVAL_TYPE = 'MINUTE TO SECOND' AND INTERVAL_PREC = 2
  AND IS_NULLABLE = 'YES';
-- PASS:0682 If count = 1?

   ROLLBACK WORK;

   DROP TABLE LOTSA_DATETIMES CASCADE;

   COMMIT WORK;

-- END TEST >>> 0682 <<< END TEST

-- *************************************************////END-OF-MODULE
