-- MODULE  DML184  

-- SQL Test Suite, V6.0, Interactive SQL, dml184.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER            

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:0897 Constraint usage redux!

   CREATE TABLE T (
     A CHAR, B CHAR, C CHAR,
     CONSTRAINT UniqueOnColsAandB UNIQUE (A, B));
-- PASS:0897 If table created successfully?

   COMMIT WORK;

   GRANT REFERENCES (A, B) ON TABLE T TO SCHANZLE;
-- PASS:0897 If grant completed successfully?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'SCHANZLE';
-- PASS:0897 If session set successfully?

   CREATE TABLE S (
     X CHAR, Y CHAR, Z CHAR,
     CONSTRAINT RefToColsAandB FOREIGN KEY (X, Y)
       REFERENCES FLATER.T (A, B));
-- PASS:0897 If table created successfully?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'FLATER';
-- PASS:0897 If session set successfully?

   SELECT CONSTRAINT_NAME
     FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
     WHERE TABLE_SCHEMA = 'FLATER' AND TABLE_NAME = 'T'
     AND CONSTRAINT_SCHEMA = 'FLATER';
-- PASS:0897 If name = 'UNIQUEONCOLSAANDB'?

   SELECT CONSTRAINT_NAME
     FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
     WHERE TABLE_SCHEMA = 'FLATER' AND TABLE_NAME = 'T'
     AND CONSTRAINT_SCHEMA = 'SCHANZLE';
-- PASS:0897 If name = 'REFTOCOLSAANDB'?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'T'
     AND (COLUMN_NAME = 'A' OR COLUMN_NAME = 'B')
     AND CONSTRAINT_SCHEMA = 'FLATER'
     AND CONSTRAINT_NAME = 'UNIQUEONCOLSAANDB';
-- PASS:0897 If COUNT = 2?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'T'
     AND (COLUMN_NAME = 'A' OR COLUMN_NAME = 'B')
     AND CONSTRAINT_SCHEMA = 'SCHANZLE'
     AND CONSTRAINT_NAME = 'REFTOCOLSAANDB';
-- PASS:0897 If COUNT = 2?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'T';
-- PASS:0897 If COUNT = 4?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'T';
-- PASS:0897 If COUNT = 2?

   COMMIT WORK;

   DROP TABLE T CASCADE;
-- PASS:0897 If table dropped successfully?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'SCHANZLE';
-- PASS:0897 If session set successfully?

   DROP TABLE S CASCADE;
-- PASS:0897 If table dropped successfully?

   COMMIT WORK;

-- END TEST >>> 0897 <<< END TEST
-- *********************************************
-- *************************************************////END-OF-MODULE
