-- MODULE  ISI007  

-- SQL Test Suite, V6.0, Interactive SQL, isi007.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER            

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:0574 Orphaned IS data structures, Intermediate SQL!

   SELECT COUNT (DISTINCT TABLE_CATALOG)
      FROM INFORMATION_SCHEMA.TABLES;
-- PASS:0574 If COUNT = 1?

   SELECT COUNT (DISTINCT TABLE_CATALOG)
     FROM INFORMATION_SCHEMA.VIEWS;
-- PASS:0574 If COUNT = 1?

   SELECT COUNT (DISTINCT TABLE_CATALOG)
     FROM INFORMATION_SCHEMA.COLUMNS;
-- PASS:0574 If COUNT = 1?

   SELECT COUNT (DISTINCT CATALOG_NAME)
     FROM INFORMATION_SCHEMA.SCHEMATA;
-- PASS:0574 If COUNT = 1?

   SELECT COUNT (DISTINCT TABLE_CATALOG)
     FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES;
-- PASS:0574 If COUNT = 1?

   SELECT COUNT (DISTINCT TABLE_CATALOG)
     FROM INFORMATION_SCHEMA.COLUMN_PRIVILEGES;
-- PASS:0574 If COUNT = 1?

   SELECT COUNT (DISTINCT OBJECT_CATALOG)
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES;
-- PASS:0574 If COUNT = 0 or 1?

   SELECT TABLE_CATALOG 
     FROM INFORMATION_SCHEMA.TABLES
     WHERE TABLE_NAME = 'WCOV';
-- PASS:0574 If select completed successfully?
-- NOTE:  REMEMBER this value of TABLE_CATALOG for later comparisons!!

   SELECT TABLE_CATALOG
     FROM INFORMATION_SCHEMA.TABLES
     ORDER BY TABLE_CATALOG;
-- PASS:0574 IF no NULLS?
-- PASS:0574 If no value = to previous "noted" TABLE_CATALOG name?

   SELECT TABLE_CATALOG
     FROM INFORMATION_SCHEMA.VIEWS
     ORDER BY TABLE_CATALOG;
-- PASS:0574 If no NULLS?
-- PASS:0574 If no value = to previous "noted" TABLE_CATALOG name?

   SELECT TABLE_CATALOG
     FROM INFORMATION_SCHEMA.COLUMNS
     ORDER BY TABLE_CATALOG;
-- PASS:0574 If no NULLS?
-- PASS:0574 If no value = to previous "noted" TABLE_CATALOG name?

   SELECT TABLE_CATALOG
     FROM INFORMATION_SCHEMA.SCHEMATA
     ORDER BY TABLE_CATALOG;
-- PASS:0574 If no NULLS?
-- PASS:0574 If no value = to previous "noted" TABLE_CATALOG name?

   SELECT TABLE_CATALOG
     FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES
     ORDER BY TABLE_CATALOG;
-- PASS:0574 If no NULLS?
-- PASS:0574 If no value = to previous "noted" TABLE_CATALOG name?

   SELECT TABLE_CATALOG
     FROM INFORMATION_SCHEMA.COLUMN_PRIVILEGES
     ORDER BY TABLE_CATALOG;
-- PASS:0574 If no NULLS?
-- PASS:0574 If no value = to previous "noted" TABLE_CATALOG name?

   SELECT TABLE_CATALOG
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
     ORDER BY TABLE_CATALOG;
-- PASS:0574 If no NULLS?
-- PASS:0574 If no value = to previous "noted" TABLE_CATALOG name?

   SELECT CHARACTER_SET_CATALOG,
        CHARACTER_SET_SCHEMA,
        CHARACTER_SET_NAME,
        COLLATION_CATALOG,
        COLLATION_SCHEMA,
        COLLATION_NAME,
        DOMAIN_CATALOG,
        DOMAIN_SCHEMA,
        DOMAIN_NAME,
        INTERVAL_TYPE,
        INTERVAL_PRECISION
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = 'FLATER'
         AND TABLE_NAME = 'USIG'
         AND COLUMN_NAME = 'C1';
-- PASS:0574 If either:  completed successfully or   ?
-- PASS:0574             WARNING - string data, right truncation?

   SELECT DEFAULT_CHARACTER_SET_CATALOG,
     DEFAULT_CHARACTER_SET_SCHEMA,
     DEFAULT_CHARACTER_SET_NAME
        FROM INFORMATION_SCHEMA.SCHEMATA
        WHERE SCHEMA_NAME = 'FLATER';
-- PASS:0574 If either:  completed successfully or  ?
-- PASS:0574             WARNING - string data, right truncation?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
     WHERE GRANTEE NOT IN ('PUBLIC', USER)
     AND GRANTOR <> USER;
-- PASS:0574 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
     WHERE PRIVILEGE_TYPE <> 'USAGE'
     OR PRIVILEGE_TYPE IS NULL;
-- PASS:0574 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
     WHERE IS_GRANTABLE IS NULL;
-- PASS:0574 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
     WHERE IS_GRANTABLE NOT IN
     ('YES', 'NO');
-- PASS:0574 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
     WHERE GRANTOR IS NULL 
     OR GRANTEE IS NULL
     OR OBJECT_SCHEMA IS NULL
     OR OBJECT_NAME IS NULL
     OR OBJECT_TYPE IS NULL;
-- PASS:0574 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES;
-- PASS:0574 If this COUNT = next COUNT?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES A,
     INFORMATION_SCHEMA.USAGE_PRIVILEGES B
     WHERE A.GRANTOR = B.GRANTOR
     AND A.GRANTEE = B.GRANTEE
     AND A.OBJECT_SCHEMA = B.OBJECT_SCHEMA
     AND A.OBJECT_NAME = B.OBJECT_NAME
     AND A.OBJECT_TYPE = B.OBJECT_TYPE;
-- PASS:0574 If this COUNT = previous COUNT?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
     WHERE (OBJECT_TYPE = 'DOMAIN' AND NOT EXISTS
       (SELECT * FROM INFORMATION_SCHEMA.DOMAINS WHERE
          OBJECT_SCHEMA = DOMAIN_SCHEMA AND
          OBJECT_NAME = DOMAIN_NAME)) OR 
     (OBJECT_TYPE = 'CHARACTER SET' AND NOT EXISTS
        (SELECT * FROM INFORMATION_SCHEMA.CHARACTER_SETS WHERE
           OBJECT_SCHEMA = CHARACTER_SET_SCHEMA AND
           OBJECT_NAME = CHARACTER_SET_NAME));
-- PASS:0574 If COUNT = 0?

   SELECT COUNT(*) 
      FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
      WHERE GRANTOR = '_SYSTEM'
        AND GRANTEE = 'PUBLIC'
        AND OBJECT_SCHEMA = 'INFORMATION_SCHEMA'
        AND OBJECT_NAME = 'SQL_TEXT'
        AND OBJECT_TYPE = 'CHARACTER SET'
        AND IS_GRANTABLE = 'YES'
        AND PRIVILEGE_TYPE = 'USAGE';
-- PASS:0574 If COUNT = 1?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
     WHERE GRANTOR = '_SYSTEM'
       AND GRANTEE = 'PUBLIC'
       AND OBJECT_SCHEMA = 'INFORMATION_SCHEMA'
       AND OBJECT_NAME = 'CARDINAL_NUMBER'
       AND OBJECT_TYPE = 'DOMAIN'
       AND IS_GRANTABLE = 'YES'
       AND PRIVILEGE_TYPE = 'USAGE';
-- PASS:0574 If COUNT = 1?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
     WHERE GRANTOR = '_SYSTEM'
       AND GRANTEE = 'PUBLIC'
       AND OBJECT_SCHEMA = 'INFORMATION_SCHEMA'
       AND OBJECT_NAME = 'SQL_IDENTIFIER'
       AND OBJECT_TYPE = 'DOMAIN'
       AND IS_GRANTABLE = 'YES'
       AND PRIVILEGE_TYPE = 'USAGE';
-- PASS:0574 If COUNT = 1?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
     WHERE GRANTOR = '_SYSTEM'
       AND GRANTEE = 'PUBLIC'
       AND OBJECT_SCHEMA = 'INFORMATION_SCHEMA'
       AND OBJECT_NAME = 'CHARACTER_DATA'
       AND OBJECT_TYPE = 'DOMAIN'
       AND IS_GRANTABLE = 'YES'
       AND PRIVILEGE_TYPE = 'USAGE';
-- PASS:0574 If COUNT = 1?

   ROLLBACK WORK;

-- END TEST >>> 0574 <<< END TEST
-- *********************************************
-- *************************************************////END-OF-MODULE
