-- MODULE  ISI002  

-- SQL Test Suite, V6.0, Interactive SQL, isi002.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER            

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:0569 INFORMATION_SCHEMA.VIEWS definition!

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE CHECK_OPTION IS NULL;
-- PASS:0569 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE IS_UPDATABLE IS NULL;
-- PASS:0569 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE IS_UPDATABLE <> 'YES'
     AND IS_UPDATABLE <> 'NO';
-- PASS:0569 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE TABLE_SCHEMA IS NULL
     OR TABLE_NAME IS NULL;
-- PASS:0569 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.VIEWS;
-- PASS:0569 If this COUNT = next COUNT?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.VIEWS A,
          INFORMATION_SCHEMA.VIEWS B
     WHERE A.TABLE_SCHEMA = B.TABLE_SCHEMA
     AND A.TABLE_NAME = B.TABLE_NAME;
-- PASS:0569 If this COUNT = previous COUNT?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.VIEWS A WHERE NOT EXISTS
     (SELECT * FROM INFORMATION_SCHEMA.TABLES B
      WHERE A.TABLE_SCHEMA = B.TABLE_SCHEMA
      AND A.TABLE_NAME = B.TABLE_NAME
      AND B.TABLE_TYPE = 'VIEW');
-- PASS:0569 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.VIEWS WHERE
     IS_UPDATABLE = 'NO' AND CHECK_OPTION <> 'NONE';
-- PASS:0569 If COUNT = 0?

   SELECT VIEW_DEFINITION 
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'DV1';
-- PASS:0569 If one of the following?
-- PASS:0569 If 'NULL'?
-- PASS:0569 If completed successfully & returned value?
-- PASS:0569 If WARNING - string data, right truncation?

   SELECT CHECK_OPTION, IS_UPDATABLE
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'DV1';
-- PASS:0569 If CHECK_OPTION = 'NONE'?
-- PASS:0569 If IS_UPDATABLE = 'YES'?

   SELECT CHECK_OPTION, IS_UPDATABLE
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'WCOV';
-- PASS:0569 If CHECK_OPTION = 'CASCADED'?
-- PASS:0569 If IS_UPDATABLE = 'YES'?

   SELECT CHECK_OPTION, IS_UPDATABLE
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'VS1';
-- PASS:0569 If CHECK_OPTION = 'NONE'?
-- PASS:0569 If IS_UPDATABLE = 'YES'?

   SELECT CHECK_OPTION, IS_UPDATABLE
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'VS2';
-- PASS:0569 If CHECK_OPTION = 'NONE'?
-- PASS:0569 IF IS_UPDATABLE = 'NO'?

   SELECT CHECK_OPTION, IS_UPDATABLE
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'VS3';
-- PASS:0569 If CHECK_OPTION = 'NONE'?
-- PASS:0569 If IS_UPDATABLE = 'NO'?

   SELECT CHECK_OPTION, IS_UPDATABLE
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'VS4';
-- PASS:0569 If CHECK_OPTION = 'NONE'?
-- PASS:0569 If IS_UPDATABLE = 'NO'?

   SELECT CHECK_OPTION, IS_UPDATABLE
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'VS5';
-- PASS:0569 IF CHECK_OPTION = 'NONE'?
-- PASS:0569 If IS_UPDATABLE = 'NO'?

   SELECT CHECK_OPTION, IS_UPDATABLE
     FROM INFORMATION_SCHEMA.VIEWS
     WHERE TABLE_SCHEMA = 'FLATER'
     AND TABLE_NAME = 'VS6';
-- PASS:0569 If CHECK_OPTION = 'NONE'?
-- PASS:0569 If IS_UPDATABLE = 'NO'?

   ROLLBACK WORK;

-- END TEST >>> 0569 <<< END TEST
-- *********************************************
-- *************************************************////END-OF-MODULE
