-- MODULE  ISI001  

-- SQL Test Suite, V6.0, Interactive SQL, isi001.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER            

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:0568 INFORMATION_SCHEMA.TABLES definition!

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.TABLES
     WHERE TABLE_TYPE IS NULL;
-- PASS:0568 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.TABLES A
     WHERE NOT EXISTS (SELECT *
          FROM INFORMATION_SCHEMA.COLUMNS B
          WHERE A.TABLE_SCHEMA = B.TABLE_SCHEMA
          AND A.TABLE_NAME = B.TABLE_NAME);
-- PASS:0568 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.TABLES
     WHERE TABLE_SCHEMA IS NULL
     OR TABLE_NAME IS NULL;
-- PASS:0568 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.TABLES;
-- PASS:0568 If this COUNT = the next COUNT?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.TABLES A, 
          INFORMATION_SCHEMA.TABLES B
     WHERE A.TABLE_SCHEMA = B.TABLE_SCHEMA
     AND A.TABLE_NAME = B.TABLE_NAME;
-- PASS:0568 If this COUNT = the previous COUNT?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.TABLES A
     WHERE NOT EXISTS (SELECT *
         FROM INFORMATION_SCHEMA.SCHEMATA B
         WHERE A.TABLE_SCHEMA = B.SCHEMA_NAME);
-- PASS:0568 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.TABLES A WHERE
     TABLE_TYPE = 'VIEW' AND NOT EXISTS
     (SELECT * FROM INFORMATION_SCHEMA.VIEWS B WHERE
      A.TABLE_SCHEMA = B.TABLE_SCHEMA
      AND A.TABLE_NAME = B.TABLE_NAME);
-- PASS:0568 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.TABLES Z WHERE NOT EXISTS
     (SELECT TABLE_SCHEMA, TABLE_NAME FROM
      INFORMATION_SCHEMA.TABLE_PRIVILEGES X
      WHERE GRANTEE IN ('PUBLIC', USER)
      AND X.TABLE_SCHEMA = Z.TABLE_SCHEMA
      AND X.TABLE_NAME = Z.TABLE_NAME
      UNION
      SELECT TABLE_SCHEMA, TABLE_NAME FROM
      INFORMATION_SCHEMA.COLUMN_PRIVILEGES Y
      WHERE GRANTEE IN ('PUBLIC', USER)
      AND Y.TABLE_SCHEMA = Z.TABLE_SCHEMA
      AND Y.TABLE_NAME = Z.TABLE_NAME);
-- PASS:0568 If COUNT = 0?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'USIG';
-- PASS:0568 If TABLE_TYPE = 'BASE TABLE'?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'U_SIG';
-- PASS:0568 If TABLE_TYPE = 'BASE TABLE'?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'DV1';
-- PASS:0568 If TABLE_TYPE = 'VIEW'?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'BASE_WCOV';
-- PASS:0568 If TABLE_TYPE = 'BASE TABLE'?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'WCOV';
-- PASS:0568 If TABLE_TYPE = 'VIEW'?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'BASE_VS1';
-- PASS:0568 If TABLE_TYPE = 'BASE TABLE'?

   SELECT TABLE_TYPE
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'VS1';
-- PASS:0568 If TABLE_TYPE = 'VIEW'?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'VS2';
-- PASS:0568 If TABLE_TYPE = 'VIEW'?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'VS3';
-- PASS:0568 If TABLE_TYPE = 'VIEW'?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'VS4';
-- PASS:0568 If TABLE_TYPE = 'VIEW'?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'VS5';
-- PASS:0568 If TABLE_TYPE = 'VIEW'?

   SELECT TABLE_TYPE 
     FROM INFORMATION_SCHEMA.TABLES WHERE
     TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'VS6';
-- PASS:0568 If TABLE_TYPE = 'VIEW'?

   ROLLBACK WORK;

-- END TEST >>> 0568 <<< END TEST
-- *********************************************
-- *************************************************////END-OF-MODULE
