-- MODULE  ISI003  

-- SQL Test Suite, V6.0, Interactive SQL, isi003.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER            

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:0570 INFORMATION_SCHEMA.COLUMNS definition!

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE ORDINAL_POSITION IS NULL;
-- PASS:0570 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA IS NULL
     OR TABLE_NAME IS NULL
     OR COLUMN_NAME IS NULL;
-- PASS:0570 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS;
-- PASS:0570 If this COUNT(referneced as COUNT1) = next COUNT?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS A,
          INFORMATION_SCHEMA.COLUMNS B
     WHERE A.TABLE_SCHEMA = B.TABLE_SCHEMA
       AND A.TABLE_NAME = B.TABLE_NAME
       AND A.COLUMN_NAME = B.COLUMN_NAME;
-- PASS:0570 If this COUNT = previous COUNT1?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS A,
          INFORMATION_SCHEMA.COLUMNS B
     WHERE A.TABLE_SCHEMA = B.TABLE_SCHEMA
       AND A.TABLE_NAME = B.TABLE_NAME
       AND A.ORDINAL_POSITION = B.ORDINAL_POSITION;
-- PASS:0570 If this COUNT = previous COUNT1?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS A
     WHERE NOT EXISTS (SELECT * FROM
           INFORMATION_SCHEMA.TABLES B WHERE
              A.TABLE_SCHEMA = B.TABLE_SCHEMA AND
              A.TABLE_NAME = B.TABLE_NAME);
-- PASS:0570 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS A
     WHERE NOT EXISTS (
     SELECT * FROM INFORMATION_SCHEMA.DOMAINS B
       WHERE A.DOMAIN_SCHEMA = B.DOMAIN_SCHEMA
         AND A.DOMAIN_NAME = B.DOMAIN_NAME)
         AND A.DOMAIN_SCHEMA IS NOT NULL;
-- PASS:0570 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE ORDINAL_POSITION < 1;
-- PASS:0570 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE (IS_NULLABLE <> 'YES'
     AND IS_NULLABLE <> 'NO')
     OR IS_NULLABLE IS NULL;
-- PASS:0570 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = 'FLATER' AND
           TABLE_NAME = 'USIG' AND
           COLUMN_NAME = 'C1' AND
           COLUMN_DEFAULT IS NULL AND
           IS_NULLABLE = 'YES' AND
           ORDINAL_POSITION = 1 AND
           DATA_TYPE = 'INTEGER' AND
           NUMERIC_SCALE = 0 AND
           CHARACTER_MAXIMUM_LENGTH IS NULL AND
           CHARACTER_OCTET_LENGTH IS NULL AND
           NUMERIC_PRECISION_RADIX IN (2, 10)
           AND DATETIME_PRECISION IS NULL;
-- PASS:0570 If COUNT = 1?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'USIG' AND
     COLUMN_NAME = 'C_1' AND
     COLUMN_DEFAULT IS NULL AND
     IS_NULLABLE = 'YES' AND
     ORDINAL_POSITION = 2 AND
     DATA_TYPE = 'INTEGER' AND
     NUMERIC_SCALE = 0 AND
     CHARACTER_MAXIMUM_LENGTH IS NULL AND
     CHARACTER_OCTET_LENGTH IS NULL AND
     NUMERIC_PRECISION_RADIX IN (2, 10)
     AND DATETIME_PRECISION IS NULL;
-- PASS:0570 If COUNT = 1?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'USIG' AND
     ORDINAL_POSITION > 2;
-- PASS:0570 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'BASE_WCOV' AND
     COLUMN_NAME = 'C1' AND
     COLUMN_DEFAULT IS NULL AND
     IS_NULLABLE = 'YES' AND
     ORDINAL_POSITION = 1 AND
     DATA_TYPE = 'INTEGER' AND
     NUMERIC_SCALE = 0 AND
     CHARACTER_MAXIMUM_LENGTH IS NULL AND
     CHARACTER_OCTET_LENGTH IS NULL AND
     NUMERIC_PRECISION_RADIX IN (2, 10)
     AND DATETIME_PRECISION IS NULL;
-- PASS:0570 If COUNT = 1?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = 'FLATER' AND
     TABLE_NAME = 'BASE_WCOV' AND
     ORDINAL_POSITION <> 1;
-- PASS:0570 If COUNT = 0?

   ROLLBACK WORK;

-- END TEST >>> 0570 <<< END TEST
-- *********************************************
-- *************************************************////END-OF-MODULE
