-- MODULE  IST005  

-- SQL Test Suite, V6.0, Interactive SQL, ist005.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER            

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:0607 INFO_SCHEM.TABLE_PRIVILEGES definition!

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTEE NOT IN ('PUBLIC', USER)
AND GRANTOR <> USER;
-- PASS:0607 If count = 0?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE IS_GRANTABLE IS NULL;
-- PASS:0607 If count = 0?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE IS_GRANTABLE NOT IN ('YES', 'NO');
-- PASS:0607 If count = 0?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR IS NULL
OR GRANTEE IS NULL
OR TABLE_SCHEM IS NULL
OR TABLE_NAME IS NULL
OR PRIVILEGE_TYPE IS NULL;
-- PASS:0607 If count = 0?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES;
-- NOTE:0607 Save this result; compare with next statement.

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES A,
INFO_SCHEM.TABLE_PRIVILEGES B
WHERE A.GRANTOR = B.GRANTOR
AND A.GRANTEE = B.GRANTEE
AND A.TABLE_SCHEM = B.TABLE_SCHEM
AND A.TABLE_NAME = B.TABLE_NAME
AND A.PRIVILEGE_TYPE = B.PRIVILEGE_TYPE;
-- PASS:0607 If count is same as that of previous statement?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES A
WHERE NOT EXISTS (
SELECT *
FROM INFO_SCHEM.TABLES B
WHERE A.TABLE_SCHEM = B.TABLE_SCHEM
AND A.TABLE_NAME = B.TABLE_NAME);
-- PASS:0607 If count = 0?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES A
WHERE EXISTS (
SELECT *
FROM INFO_SCHEM.TABLES B
WHERE A.TABLE_SCHEM = B.TABLE_SCHEM
AND A.TABLE_NAME = B.TABLE_NAME);
-- PASS:0607 If count > 5?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = '_SYSTEM'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'USIG'
AND PRIVILEGE_TYPE = 'SELECT';
-- PASS:0607 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = '_SYSTEM'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'USIG'
AND PRIVILEGE_TYPE = 'INSERT';
-- PASS:0607 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = '_SYSTEM'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'USIG'
AND PRIVILEGE_TYPE = 'UPDATE';
-- PASS:0607 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = '_SYSTEM'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'USIG'
AND PRIVILEGE_TYPE = 'DELETE';
-- PASS:0607 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = '_SYSTEM'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'USIG'
AND PRIVILEGE_TYPE = 'REFERENCES';
-- PASS:0607 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = 'FLATER'
AND GRANTEE = 'SCHANZLE'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'WCOV'
AND PRIVILEGE_TYPE = 'SELECT';
-- PASS:0607 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = 'FLATER'
AND GRANTEE = 'SCHANZLE'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'WCOV'
AND PRIVILEGE_TYPE = 'INSERT';
-- PASS:0607 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = 'FLATER'
AND GRANTEE = 'SCHANZLE'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'WCOV'
AND PRIVILEGE_TYPE = 'UPDATE';
-- PASS:0607 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = 'FLATER'
AND GRANTEE = 'SCHANZLE'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'WCOV'
AND PRIVILEGE_TYPE = 'DELETE';
-- PASS:0607 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = 'FLATER'
AND GRANTEE = 'SCHANZLE'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'WCOV'
AND PRIVILEGE_TYPE = 'REFERENCES';
-- PASS:0607 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = 'HU'
AND GRANTEE = 'PUBLIC'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'HU'
AND TABLE_NAME = 'TESTREPORT'
AND PRIVILEGE_TYPE = 'INSERT';
-- PASS:0607 If count = 1?

SELECT COUNT(*)
FROM INFO_SCHEM.TABLE_PRIVILEGES
WHERE GRANTOR = 'HU'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'HU'
AND TABLE_NAME = 'STAFF4'
AND PRIVILEGE_TYPE = 'DELETE';
-- PASS:0607 If count = 1?

ROLLBACK;

-- END TEST >>> 0607 <<< END TEST

-- *************************************************////END-OF-MODULE
