-- MODULE  IST006  

-- SQL Test Suite, V6.0, Interactive SQL, ist006.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER            

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:0608 INFO_SCHEM.COLUMN_PRIVILEGES definition!

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTEE NOT IN ('PUBLIC', USER)
AND GRANTOR <> USER;
-- PASS:0608 If count = 0?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE IS_GRANTABLE IS NULL;
-- PASS:0608 If count = 0?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE IS_GRANTABLE NOT IN ('YES', 'NO');
-- PASS:0608 If count = 0?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR IS NULL
OR GRANTEE IS NULL
OR TABLE_SCHEM IS NULL
OR TABLE_NAME IS NULL
OR PRIVILEGE_TYPE IS NULL
OR COLUMN_NAME IS NULL;
-- PASS:0608 If count = 0?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES;
-- NOTE:0608 Save this result; compare with next statement.

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES A,
INFO_SCHEM.COLUMN_PRIVILEGES B
WHERE A.GRANTOR = B.GRANTOR
AND A.GRANTEE = B.GRANTEE
AND A.TABLE_SCHEM = B.TABLE_SCHEM
AND A.TABLE_NAME = B.TABLE_NAME
AND A.PRIVILEGE_TYPE = B.PRIVILEGE_TYPE
AND A.COLUMN_NAME = B.COLUMN_NAME;
-- PASS:0608 If count is same as that of previous statement?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES A
WHERE NOT EXISTS (
SELECT * FROM INFO_SCHEM.COLUMNS B
WHERE A.TABLE_SCHEM = B.TABLE_SCHEM
AND A.TABLE_NAME = B.TABLE_NAME
AND A.COLUMN_NAME = B.COLUMN_NAME);
-- PASS:0608 If count = 0?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR = '_SYSTEM'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'USIG'
AND COLUMN_NAME = 'C_1'
AND PRIVILEGE_TYPE = 'SELECT';
-- PASS:0608 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR = '_SYSTEM'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'USIG'
AND COLUMN_NAME = 'C_1'
AND PRIVILEGE_TYPE = 'INSERT';
-- PASS:0608 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR = '_SYSTEM'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'USIG'
AND COLUMN_NAME = 'C_1'
AND PRIVILEGE_TYPE = 'UPDATE';
-- PASS:0608 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR = '_SYSTEM'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'USIG'
AND COLUMN_NAME = 'C_1'
AND PRIVILEGE_TYPE = 'REFERENCES';
-- PASS:0608 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR = 'FLATER'
AND GRANTEE = 'SCHANZLE'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'WCOV'
AND COLUMN_NAME = 'C1'
AND PRIVILEGE_TYPE = 'SELECT';
-- PASS:0608 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR = 'FLATER'
AND GRANTEE = 'SCHANZLE'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'WCOV'
AND COLUMN_NAME = 'C1'
AND PRIVILEGE_TYPE = 'INSERT';
-- PASS:0608 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR = 'FLATER'
AND GRANTEE = 'SCHANZLE'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'WCOV'
AND COLUMN_NAME = 'C1'
AND PRIVILEGE_TYPE = 'UPDATE';
-- PASS:0608 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR = 'FLATER'
AND GRANTEE = 'SCHANZLE'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'FLATER'
AND TABLE_NAME = 'WCOV'
AND COLUMN_NAME = 'C1'
AND PRIVILEGE_TYPE = 'REFERENCES';
-- PASS:0608 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR = 'HU'
AND GRANTEE = 'PUBLIC'
AND IS_GRANTABLE = 'YES'
AND TABLE_SCHEM = 'HU'
AND TABLE_NAME = 'TESTREPORT'
AND COLUMN_NAME = 'RESULT'
AND PRIVILEGE_TYPE = 'INSERT';
-- PASS:0608 If count = 1?

   SELECT COUNT(*)
FROM INFO_SCHEM.COLUMN_PRIVILEGES
WHERE GRANTOR = 'HU'
AND GRANTEE = 'FLATER'
AND IS_GRANTABLE = 'NO'
AND TABLE_SCHEM = 'HU'
AND TABLE_NAME = 'STAFF4'
AND COLUMN_NAME = 'EMPNAME'
AND PRIVILEGE_TYPE = 'INSERT';
-- PASS:0608 If count = 1?

ROLLBACK;

-- END TEST >>> 0608 <<< END TEST

-- *************************************************////END-OF-MODULE
