-- ***************************************************************
-- ****** THIS FILE SHOULD BE RUN UNDER AUTHORIZATION ID FLATER **
-- ***************************************************************
-- MODULE  SC11TAB

-- SQL Test Suite, V6.0, Interactive SQL, sc11tab.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment

-- date_time print

-- This routine initializes the contents of tables:
--     STATIONS, CCONV in schema HYDROGRAPHY
-- This routine may be run at any time to re-initialize tables.

   DELETE FROM HYDROGRAPHY.STATIONS;

   INSERT INTO HYDROGRAPHY.STATIONS VALUES (9962420, 1,
   'EASTER ISLAND, HANGA PIKO HARBOR', '27  9.0S', '109 26.9W',
   INTERVAL -'7:00' HOUR TO MINUTE, 1.5E0, NULL);

   INSERT INTO HYDROGRAPHY.STATIONS VALUES (9452210, 0,
   'JUNEAU, GASTINEAU CHANNEL, STEPHENS', '58 17.9N', '134 24.7W',
   INTERVAL -'9:00' HOUR TO MINUTE, 5.62E0, NULL);
   
   INSERT INTO HYDROGRAPHY.STATIONS VALUES (9414290, 0,
   'SAN FRANCISCO, SAN FRANCISCO BAY', '37 48.4N', '122 27.9W',
   INTERVAL -'8:00' HOUR TO MINUTE, 3.13E0, -0.2);
   
   INSERT INTO HYDROGRAPHY.STATIONS VALUES (1495000, 1,
   'ESPERANZA, ANTARCTICA', '63 23.7S', '56  59.7W',
   NULL, NULL, NULL);
   
   INSERT INTO HYDROGRAPHY.STATIONS VALUES (1495000, 2,
   'ESPERANZA, ANTARCTICA', '63 23.7S', '56  59.7W',
   NULL, NULL, NULL);
   
   INSERT INTO HYDROGRAPHY.STATIONS VALUES (0670001, 0,
   'NAHA HARBOR, OKINAWA', '26 12.5N', '127 40.1E',
   INTERVAL '9:00' HOUR TO MINUTE, 1.18E0, NULL);

   SELECT COUNT(*) FROM HYDROGRAPHY.STATIONS;
-- PASS:Setup If count = 6?

   DELETE FROM HYDROGRAPHY.CCONV;

   INSERT INTO HYDROGRAPHY.CCONV VALUES ('N', 1E0);

   INSERT INTO HYDROGRAPHY.CCONV VALUES ('S', -1E0);

   INSERT INTO HYDROGRAPHY.CCONV VALUES ('E', 1E0);

   INSERT INTO HYDROGRAPHY.CCONV VALUES ('W', -1E0);

   SELECT COUNT(*) FROM HYDROGRAPHY.CCONV;
-- PASS:Setup If count = 4?

   COMMIT WORK;
-- *************************************************////END-OF-MODULE
