-- MODULE SDL026BYADDING12CH

-- SQL Test Suite, V6.0, Interactive SQL, sdl026.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION CANWEPARSELENGTH18

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment

-- date_time print

-- TEST:0237 FIPS sizing - identifier length 18!

     DELETE FROM CHARACTER18TABLE18;

-- setup
     INSERT INTO CHARACTERS18VIEW18 
            VALUES ('VALU');
-- PASS:0237 If 1 row is inserted?

     COMMIT WORK;

     UPDATE CHARACTER18TABLE18 
          SET CHARS18NAME18CHARS = 'VAL4' 
          WHERE CHARS18NAME18CHARS = 'VALU';
-- PASS:0237 If 1 row is updated?

     COMMIT WORK;

     SELECT * 
          FROM CANWEPARSELENGTH18.CHARACTERS18VIEW18;
-- PASS:0237 If LONGNAME18LONGNAME = 'VAL4' ?

     SELECT CORRELATIONNAMES18.CHARS18NAME18CHARS
          FROM CHARACTER18TABLE18 CORRELATIONNAMES18
          WHERE CORRELATIONNAMES18.CHARS18NAME18CHARS = 'VAL4';
-- PASS:0237 If CORRELATIONNAMES18.CHARS18NAME18CHARS = 'VAL4'?

-- restore
      DELETE FROM CHARACTER18TABLE18;
      COMMIT WORK;

-- END TEST >>> 0237 <<< END TEST
-- *************************************************////END-OF-MODULE
