-- MODULE   XTS744

-- SQL Test Suite, V6.0, Interactive SQL, xts744.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION CTS1              

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:7044 Presence of SQL_CHARACTER in CHARACTER_SETS view!

   SELECT CHARACTER_SET_SCHEMA,
         CHARACTER_SET_NAME,NUMBER_OF_CHARACTERS,CHARACTER_SET_CATALOG,
         DEFAULT_COLLATE_CATALOG, DEFAULT_COLLATE_SCHEMA,
         DEFAULT_COLLATE_NAME FROM INFORMATION_SCHEMA.CHARACTER_SETS
         WHERE CHARACTER_SET_SCHEMA = 'INFORMATION_SCHEMA'
         AND CHARACTER_SET_NAME = 'SQL_CHARACTER';
-- PASS:7044 If CHARACTER_SET_SCHEMA = INFORMATION SCHEMA?
-- PASS:7044 If CHARACTER_SET_NAME = SQL_CHARACTER?
-- PASS:7044 If NUMBER_OF_CHARACTERS = 83?
-- PASS:7044 If CHARACTER_SET_CATALOG not NULL?
-- PASS:7044 If DEFAULT_COLLATE_CATALOG not NULL?
-- PASS:7044 If DEFAULT_COLLATE_SCHEMA not NULL?
-- PASS:7044 If DEFAULT_COLLATE_NAME not NULL?

   ROLLBACK WORK;

-- END TEST >>> 7044 <<< END TEST
-- *********************************************
-- *************************************************////END-OF-MODULE
