-- MODULE  YTS766  

-- SQL Test Suite, V6.0, Interactive SQL, yts766.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION CTS1              

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:7540 Explicit table constraints - REFERENTIAL_CONSTRAINTS!

   SELECT CONSTRAINT_NAME 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE TABLE_NAME = 'WORKS3A' AND 
     CONSTRAINT_TYPE = 'FOREIGN KEY';
-- PASS:7540 If select completed successfully?

   SELECT CONSTRAINT_NAME, UNIQUE_CONSTRAINT_SCHEMA, 
     MATCH_OPTION,UPDATE_RULE,DELETE_RULE 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     ORDER BY CONSTRAINT_NAME;
-- PASS:7540 If CONST_NAME = previous CONST_NAME for exactly 1 row?
-- NOTE:  UNIQUE_CONSTRAINT_SCHEMA is implementor defined and may
--        be any value.
-- PASS:7540 If MATCH_OPTION = NONE? 
-- PASS:7540 If UPDATE_RULE = NO ACTION?
-- PASS:7540 If DELETE_RULE = NO ACTION?

   SELECT CONSTRAINT_NAME 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE TABLE_NAME = 'COMP_BUDG' AND
     CONSTRAINT_TYPE = 'FOREIGN KEY';
-- PASS:7540 If select completed successfully?

   SELECT CONSTRAINT_NAME, UNIQUE_CONSTRAINT_SCHEMA, 
     MATCH_OPTION,UPDATE_RULE,DELETE_RULE 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     ORDER BY CONSTRAINT_NAME;
-- PASS:7540 If CONST_NAME = previous CONST_NAME for exactly 1 row?
-- NOTE:  UNIQUE_CONSTRAINT_SCHEMA is implementor defined and may
--        be any value.
-- PASS:7540 If MATCH_OPTION = NONE? 
-- PASS:7540 If UPDATE_RULE = NO ACTION?
-- PASS:7540 If DELETE_RULE = NO ACTION?

   ROLLBACK WORK;

-- END TEST >>> 7540 <<< END TEST
-- *********************************************

-- TEST:7541 Column constraints in REFERENTIAL_CONSTRAINTS view!

   SELECT CONSTRAINT_NAME 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE TABLE_NAME = 'STAFFZ' AND
     CONSTRAINT_TYPE = 'FOREIGN KEY';
-- PASS:7541 If select completed successfully?

   SELECT CONSTRAINT_NAME, UNIQUE_CONSTRAINT_SCHEMA, 
     MATCH_OPTION,UPDATE_RULE, DELETE_RULE 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
     ORDER BY CONSTRAINT_NAME;
-- PASS:7541 If CONST_NAME = previous CONST_NAME for exactly 1 row?
-- NOTE:  UNIQUE_CONSTRAINT_SCHEMA is implementor defined and may
--        be any value.
-- PASS:7541 If MATCH_OPTION = NONE? 
-- PASS:7541 If UPDATE_RULE = NO ACTION?
-- PASS:7541 If DELETE_RULE = NO ACTION?

   SELECT CONSTRAINT_NAME 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE TABLE_NAME = 'PROJ_STATUS' AND
     CONSTRAINT_TYPE = 'FOREIGN KEY';
-- PASS:7541 If select completed successfully?

   SELECT CONSTRAINT_NAME, UNIQUE_CONSTRAINT_SCHEMA, 
     MATCH_OPTION, UPDATE_RULE, DELETE_RULE 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
     ORDER BY CONSTRAINT_NAME;
-- PASS:7541 If CONST_NAME = previous CONST_NAME for exactly 1 row?
-- NOTE:  UNIQUE_CONSTRAINT_SCHEMA is implementor defined and may 
--        be any value.
-- PASS:7541 If MATCH_OPTION = NONE? 
-- PASS:7541 If UPDATE_RULE = NO ACTION?
-- PASS:7541 If DELETE_RULE = NO ACTION?

   ROLLBACK WORK;

-- END TEST >>> 7541 <<< END TEST
-- *********************************************

-- TEST:7542 Unique id in REFERENTIAL_CONSTRAINTS view!

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE CONSTRAINT_CATALOG IS NULL;
-- PASS:7542 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE CONSTRAINT_SCHEMA IS NULL;
-- PASS:7542 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE CONSTRAINT_NAME IS NULL;
-- PASS:7542 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS;
-- PASS:7542 If this COUNT is = to the next COUNT?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS T
     WHERE
     UNIQUE (
         SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
         WHERE CONSTRAINT_CATALOG = T.CONSTRAINT_CATALOG AND
         CONSTRAINT_NAME = T.CONSTRAINT_NAME AND
         CONSTRAINT_SCHEMA = T.CONSTRAINT_SCHEMA
            );
-- PASS:7542 If this COUNT is = to the previous COUNT?

   ROLLBACK WORK;

-- END TEST >>> 7542 <<< END TEST
-- *********************************************

-- TEST:7543 Values in columns of REFERENTIAL_CONSTRAINTS view!

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE UNIQUE_CONSTRAINT_CATALOG IS NULL;
-- PASS:7543 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE UNIQUE_CONSTRAINT_SCHEMA IS NULL;
-- PASS:7543 If COUNT = 0?

   SELECT COUNT(*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE UNIQUE_CONSTRAINT_NAME IS NULL;
-- PASS:7543 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE MATCH_OPTION IS NULL;
-- PASS:7543 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE UPDATE_RULE IS NULL;
-- PASS:7543 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE DELETE_RULE IS NULL;
-- PASS:7543 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS;
-- PASS:7543 If    this COUNT (referenced as COUNT#1) is = to   ?
-- PASS:7543       the next three COUNTs                        ?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE MATCH_OPTION IN ('NONE','PARTIAL','FULL');
-- PASS:7543 If this COUNT is = to the previous COUNT#1?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE UPDATE_RULE IN
     ('CASCADE','SET NULL','SET DEFAULT','NO ACTION');
-- PASS:7543 If this COUNT is = to the previous COUNT#1?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
     WHERE DELETE_RULE IN
     ('CASCADE','SET NULL','SET DEFAULT','NO ACTION');
-- PASS:7543 If this COUNT is = to the previous COUNT#1?

   ROLLBACK WORK;

-- END TEST >>> 7543 <<< END TEST
-- *********************************************
-- *************************************************////END-OF-MODULE
