-- MODULE  YTS765  

-- SQL Test Suite, V6.0, Interactive SQL, yts765.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION CTS1              

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:7537 Explicit table constraints in TABLE_CONSTRAINTS view!

   SELECT CONSTRAINT_SCHEMA, TABLE_SCHEMA,
     IS_DEFERRABLE, INITIALLY_DEFERRED 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     WHERE TABLE_NAME = 'WORKS3A' AND 
     CONSTRAINT_TYPE = 'FOREIGN KEY';
-- NOTE: CONSTRAINT_SCHEMA is implementor defined & may be any value.
-- PASS:7537 If TABLE_SCHEMA = CTS1?
-- PASS:7537 If IS_DEFFERRABLE = NO?
-- PASS:7537 If INITIALLY_DEFERRED = NO? 

   SELECT CONSTRAINT_SCHEMA, TABLE_SCHEMA, 
     IS_DEFERRABLE, INITIALLY_DEFERRED 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     WHERE TABLE_NAME = 'WORKS' AND CONSTRAINT_TYPE = 'UNIQUE';
-- PASS:7537 If TABLE_SCHEMA = CTS1?
-- PASS:7537 If IS_DEFERRABLE = NO?
-- PASS:7537 If INITIALLY_DEFERRED = NO?

   SELECT CONSTRAINT_SCHEMA, TABLE_SCHEMA, 
     IS_DEFERRABLE, INITIALLY_DEFERRED 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     WHERE TABLE_NAME = 'STAFF7' AND CONSTRAINT_TYPE = 'PRIMARY KEY';
-- PASS:7537 If TABLE_SCHEMA = CTS1?
-- PASS:7537 If IS_DEFERRABLE = NO?
-- PASS:7537 If INITIALLY_DEFERRED = NO?

   SELECT CONSTRAINT_SCHEMA, TABLE_SCHEMA,
     IS_DEFERRABLE, INITIALLY_DEFERRED 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     WHERE TABLE_NAME = 'STAFF7' AND CONSTRAINT_TYPE = 'CHECK';
-- PASS:7537 If TABLE_SCHEMA = CTS1?
-- PASS:7537 If IS_DEFERRABLE = NO?
-- PASS:7537 If INITIALLY_DEFERRED = NO?

   ROLLBACK WORK;

-- END TEST >>> 7537 <<< END TEST
-- *********************************************

-- TEST:7538 Column constraints in TABLE_CONSTRAINTS view!

   SELECT CONSTRAINT_SCHEMA, TABLE_SCHEMA, 
     IS_DEFERRABLE, INITIALLY_DEFERRED 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     WHERE TABLE_NAME = 'STAFF1' AND CONSTRAINT_TYPE = 'CHECK';
-- PASS:7538 If TABLE_SCHEMA = CTS1?
-- PASS:7538 If IS_DEFERRABLE = NO?
-- PASS:7538 If INITIALLY_DEFERRED = NO?

   SELECT CONSTRAINT_SCHEMA, TABLE_SCHEMA, 
     IS_DEFERRABLE, INITIALLY_DEFERRED 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     WHERE TABLE_NAME = 'STAFF' AND CONSTRAINT_TYPE = 'UNIQUE';
-- PASS:7538 If TABLE_SCHEMA = CTS1?
-- PASS:7538 If IS_DEFERRABLE = NO?
-- PASS:7538 If INITIALLY_DEFERRED = NO?

   SELECT CONSTRAINT_SCHEMA, TABLE_SCHEMA, 
     IS_DEFERRABLE, INITIALLY_DEFERRED 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     WHERE TABLE_NAME = 'STAFFZ' AND CONSTRAINT_TYPE = 'FOREIGN KEY';
-- PASS:7538 If TABLE_SCHEMA = CTS1?
-- PASS:7538 If IS_DEFERRABLE = NO?
-- PASS:7538 If INITIALLY_DEFERRED = NO?

   SELECT CONSTRAINT_SCHEMA, TABLE_SCHEMA,
     IS_DEFERRABLE, INITIALLY_DEFERRED 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
     WHERE TABLE_NAME = 'STAFFZ' AND CONSTRAINT_TYPE = 'CHECK';
-- PASS:7538 If TABLE_SCHEMA = CTS1?
-- PASS:7538 If IS_DEFERRABLE = NO?
-- PASS:7538 If INITIALLY_DEFERRED = NO?

   ROLLBACK WORK;

-- END TEST >>> 7538 <<< END TEST
-- *********************************************

-- TEST:7539 Unique identification in TABLE_CONSTRAINTS view!

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE CONSTRAINT_CATALOG IS NULL;
-- PASS:7539 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE CONSTRAINT_SCHEMA IS NULL;
-- PASS:7539 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE CONSTRAINT_NAME IS NULL;
-- PASS:7539 If COUNT = 0?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS;
-- PASS:7539 If this COUNT is = to the next COUNT?

   SELECT COUNT (*) 
     FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS T
     WHERE
     UNIQUE (
         SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
         WHERE CONSTRAINT_CATALOG = T.CONSTRAINT_CATALOG AND
         CONSTRAINT_NAME = T.CONSTRAINT_NAME AND
         CONSTRAINT_SCHEMA = T.CONSTRAINT_SCHEMA
            );
-- PASS:7539 If this COUNT is = to the previous COUNT?

   ROLLBACK WORK;

-- END TEST >>> 7539 <<< END TEST
-- *********************************************
-- *************************************************////END-OF-MODULE
