# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: false
  Python: false
exclude_paths:
- "**/deps/**"
- "**/node_modules/**"
- "**/vendor/**"
- "**/**-min-**"
- "**/**-min.**"
- "**/**.min.**"
- "**/**jquery.?(ui|effects)-*.*.?(*).?(cs|j)s"
- "**/**jquery-*.*.?(*).?(cs|j)s"
- "**/prototype?(*).js"
- "**/**.test"
- "console/**"
- "dist/**"
- "examples/**"
- "meteor/**"
- "lib/**"
- "stuff/**"
- "test-sql/**"
- "test/**"
- "utils/**"
- "alasql.js"
- "gulpfile.js"
- "**/**_.js"
