/** @type {import('jest').Config} */
module.exports = {
	testEnvironment: 'node',
	testMatch: ['<rootDir>/test/**/*.js'],
	testPathIgnorePatterns: [
		'/node_modules/',
		'<rootDir>/test/lib/',
		'<rootDir>/test/coverage/',
		'<rootDir>/test/performance/',
		'<rootDir>/test/skip/',
		'<rootDir>/test/browserTestRunner.js',
		// jest-setup.js is a setup file, not a test file
		'<rootDir>/test/jest-setup.js',
		// test.js is the Mocha entry point, not a test suite
		'<rootDir>/test/test.js',
		// Browser-only tests (describe block inside `if (typeof exports != 'object')`)
		'<rootDir>/test/test145.js',
		'<rootDir>/test/test153.js',
		'<rootDir>/test/test154.js',
		'<rootDir>/test/test155.js',
		'<rootDir>/test/test158.js',
		'<rootDir>/test/test161.js',
		'<rootDir>/test/test208.js',
		'<rootDir>/test/test211.js',
		'<rootDir>/test/test405.js',
		'<rootDir>/test/test845-B.js',
		'<rootDir>/test/test1409.js',
		'<rootDir>/test/test1556.js',
		'<rootDir>/test/test1641.js',
		'<rootDir>/test/test2361.js',
		// Disabled tests (describe block inside `if (false)` or similar, no active tests)
		'<rootDir>/test/test051.js',
		'<rootDir>/test/test057.js',
		'<rootDir>/test/test058.js',
		'<rootDir>/test/test067.js',
		'<rootDir>/test/test068.js',
		'<rootDir>/test/test069.js',
		'<rootDir>/test/test070.js',
		'<rootDir>/test/test071.js',
		'<rootDir>/test/test072.js',
		'<rootDir>/test/test073.js',
		'<rootDir>/test/test074.js',
		'<rootDir>/test/test075.js',
		'<rootDir>/test/test076.js',
		'<rootDir>/test/test077.js',
		'<rootDir>/test/test078.js',
		'<rootDir>/test/test079.js',
		'<rootDir>/test/test080.js',
		'<rootDir>/test/test081.js',
		'<rootDir>/test/test082.js',
		'<rootDir>/test/test083.js',
		'<rootDir>/test/test084.js',
		'<rootDir>/test/test085.js',
		'<rootDir>/test/test086.js',
		'<rootDir>/test/test087.js',
		'<rootDir>/test/test088.js',
		'<rootDir>/test/test089.js',
		'<rootDir>/test/test090.js',
		'<rootDir>/test/test091.js',
		'<rootDir>/test/test093.js',
		'<rootDir>/test/test094.js',
		'<rootDir>/test/test095.js',
		'<rootDir>/test/test096.js',
		'<rootDir>/test/test097.js',
		'<rootDir>/test/test098.js',
		'<rootDir>/test/test099.js',
		'<rootDir>/test/test100.js',
		'<rootDir>/test/test101.js',
		'<rootDir>/test/test102.js',
		'<rootDir>/test/test103.js',
		'<rootDir>/test/test104.js',
		'<rootDir>/test/test105.js',
		'<rootDir>/test/test131.js',
		'<rootDir>/test/test134.js',
		'<rootDir>/test/test135.js',
		'<rootDir>/test/test136.js',
		'<rootDir>/test/test163.js',
		'<rootDir>/test/test166.js',
		'<rootDir>/test/test167.js',
		'<rootDir>/test/test173.js',
		'<rootDir>/test/test186.js',
		'<rootDir>/test/test016a.js',
		'<rootDir>/test/test222.js',
		'<rootDir>/test/test239.js',
		'<rootDir>/test/test160.js',
	],
	setupFilesAfterEnv: ['<rootDir>/test/jest-setup.js'],
	maxWorkers: 1,
	testTimeout: 30000,
};
