-- MODULE  IST002  

-- SQL Test Suite, V6.0, Interactive SQL, ist002.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION FLATER

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:0604 INFO_SCHEM.VIEWS definition!

-- Verify CONSTRAINT CHECK_OPTION_NOT_NULL
   SELECT COUNT(*) FROM INFO_SCHEM.VIEWS
   WHERE CHECK_OPTION IS NULL;
-- PASS:0604 If count = 0?

-- Verify CONSTRAINT IS_UPDATABLE_NOT_NULL
   SELECT COUNT(*) FROM INFO_SCHEM.VIEWS
   WHERE IS_UPDATABLE IS NULL;
-- PASS:0604 If count = 0?

-- Verify CONSTRAINT IS_UPDATABLE_CHECK
   SELECT COUNT(*) FROM INFO_SCHEM.VIEWS
   WHERE IS_UPDATABLE <> 'YES'
   AND IS_UPDATABLE <> 'NO';
-- PASS:0604 If count = 0?

-- Verify CONSTRAINT VIEWS_PRIMARY_KEY
   SELECT COUNT(*) FROM INFO_SCHEM.VIEWS
   WHERE TABLE_SCHEM IS NULL
   OR TABLE_NAME IS NULL;
-- PASS:0604 If count = 0?

   SELECT COUNT(*) FROM INFO_SCHEM.VIEWS;
-- PASS:0604 If count is same as that of next statement?

   SELECT COUNT(*) FROM INFO_SCHEM.VIEWS A,
   INFO_SCHEM.VIEWS B WHERE A.TABLE_SCHEM = B.TABLE_SCHEM
   AND A.TABLE_NAME = B.TABLE_NAME;
-- PASS:0604 If count is same as that of previous statement?

-- Verify CONSTRAINT VIEWS_IN_TABLES_CHECK
   SELECT COUNT(*) FROM INFO_SCHEM.VIEWS A WHERE NOT EXISTS
   (SELECT * FROM INFO_SCHEM.TABLES B
   WHERE A.TABLE_SCHEM = B.TABLE_SCHEM
   AND A.TABLE_NAME = B.TABLE_NAME
   AND B.TABLE_TYPE = 'VIEW');
-- PASS:0604 If count = 0?

-- Verify CONSTRAINT VIEWS_IS_UPDATABLE_CHECK_OPTION_CHECK
   SELECT COUNT(*) FROM INFO_SCHEM.VIEWS WHERE
   IS_UPDATABLE = 'NO' AND CHECK_OPTION <> 'NONE';
-- PASS:0604 If count = 0?

-- Make sure VIEW_DEFINITION is there.
   SELECT VIEW_DEFINITION FROM INFO_SCHEM.VIEWS
   WHERE TABLE_SCHEM = 'FLATER'
   AND TABLE_NAME = 'DV1';
-- PASS:0604 If 1 row selected?

-- Verify the metadata on a few boring views; no fancy features.
   SELECT CHECK_OPTION, IS_UPDATABLE FROM INFO_SCHEM.VIEWS
   WHERE TABLE_SCHEM = 'FLATER'
   AND TABLE_NAME = 'DV1';
-- PASS:0604 If 1 row selected AND CHECK_OPTION = NONE?
-- PASS:0604 AND IS_UPDATABLE = YES?

   SELECT CHECK_OPTION, IS_UPDATABLE FROM INFO_SCHEM.VIEWS
   WHERE TABLE_SCHEM = 'FLATER'
   AND TABLE_NAME = 'WCOV';
-- PASS:0604 If 1 row selected AND CHECK_OPTION = CASCADED?
-- PASS:0604 AND IS_UPDATABLE = YES?

   SELECT CHECK_OPTION, IS_UPDATABLE FROM INFO_SCHEM.VIEWS
   WHERE TABLE_SCHEM = 'FLATER'
   AND TABLE_NAME = 'VS1';
-- PASS:0604 If 1 row selected AND CHECK_OPTION = NONE?
-- PASS:0604 AND IS_UPDATABLE = YES?

   SELECT CHECK_OPTION, IS_UPDATABLE FROM INFO_SCHEM.VIEWS
   WHERE TABLE_SCHEM = 'FLATER'
   AND TABLE_NAME = 'VS2';
-- PASS:0604 If 1 row selected AND CHECK_OPTION = NONE?
-- PASS:0604 AND IS_UPDATABLE = NO?

   SELECT CHECK_OPTION, IS_UPDATABLE FROM INFO_SCHEM.VIEWS
   WHERE TABLE_SCHEM = 'FLATER'
   AND TABLE_NAME = 'VS3';
-- PASS:0604 If 1 row selected AND CHECK_OPTION = NONE?
-- PASS:0604 AND IS_UPDATABLE = NO?

   SELECT CHECK_OPTION, IS_UPDATABLE FROM INFO_SCHEM.VIEWS
   WHERE TABLE_SCHEM = 'FLATER'
   AND TABLE_NAME = 'VS4';
-- PASS:0604 If 1 row selected AND CHECK_OPTION = NONE?
-- PASS:0604 AND IS_UPDATABLE = NO?

   SELECT CHECK_OPTION, IS_UPDATABLE FROM INFO_SCHEM.VIEWS
   WHERE TABLE_SCHEM = 'FLATER'
   AND TABLE_NAME = 'VS5';
-- PASS:0604 If 1 row selected AND CHECK_OPTION = NONE?
-- PASS:0604 AND IS_UPDATABLE = NO?

   SELECT CHECK_OPTION, IS_UPDATABLE FROM INFO_SCHEM.VIEWS
   WHERE TABLE_SCHEM = 'FLATER'
   AND TABLE_NAME = 'VS6';
-- PASS:0604 If 1 row selected AND CHECK_OPTION = NONE?
-- PASS:0604 AND IS_UPDATABLE = NO?

   ROLLBACK WORK;

-- END TEST >>> 0604 <<< END TEST
-- *************************************************////END-OF-MODULE
