-- MODULE   XTS765

-- SQL Test Suite, V6.0, Interactive SQL, xts765.sql
-- 59-byte ID
-- TEd Version #

-- AUTHORIZATION CTS1              

   SELECT USER FROM HU.ECCO;
-- RERUN if USER value does not match preceding AUTHORIZATION comment
   ROLLBACK WORK;

-- date_time print

-- TEST:7065 REVOKE USAGE on character set CASCADE!

   GRANT USAGE ON CHARACTER SET CS TO CTS2 
         WITH GRANT OPTION;
-- PASS:7065 If usage granted successfully?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS2';
-- PASS:7065 If statement completed successfully?

   CREATE TABLE TEMP765A 
         (COLCH1 CHAR(10) CHARACTER SET CTS1.CS,
          COLN NUMERIC(5));
-- PASS:7065 If table created successfully?

   COMMIT WORK;

   GRANT USAGE ON CHARACTER SET CTS1.CS TO CTS3;
-- PASS:7065 If usage granted successfully?

   COMMIT WORK;

   SELECT TABLE_NAME, COLUMN_NAME, CHARACTER_SET_NAME,
         ORDINAL_POSITION
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLCH1';
-- PASS:7065 If TABLE_NAME = TEMP765A?
-- PASS:7065 If COLUMN_NAME = COLCH1?
-- PASS:7065 If CHARACTER_SET_NAME = CS?
-- PASS:7065 If ORDINAL_POSITION = 1?

   SELECT TABLE_NAME, COLUMN_NAME,
         ORDINAL_POSITION
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLN';
-- PASS:7065 If TABLE_NAME = TEMP765A?
-- PASS:7065 If COLUMN_NAME = COLN?
-- PASS:7065 If ORDINAL POSITION = 2?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS3';
-- PASS:7065 If statement completed successfully?

   CREATE TABLE TEMP765B 
         (COLSTR1 CHAR(10) CHARACTER SET CTS1.CS,
          COLNUM1 DECIMAL(4));
-- PASS:7065 If table created successfully?

   COMMIT WORK;

   SELECT TABLE_NAME, COLUMN_NAME, CHARACTER_SET_NAME,
         ORDINAL_POSITION
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLSTR1';
-- PASS:7065 If TABLE_NAME = TEMP765B?
-- PASS:7065 If COLUMN_NAME = COLSTR1?
-- PASS:7065 If CHARACTER_SET_NAME = CS?
-- PASS:7065 If ORDINAL_POSITION = 1?

   SELECT TABLE_NAME, COLUMN_NAME,
         ORDINAL_POSITION
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLNUM1';
-- PASS:7065 If TABLE_NAME = TEMP765B?
-- PASS:7065 If COLUMN_NAME = COLNUM1?
-- PASS:7065 If ORDINAL_POSITION = 2?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS1';
-- PASS:7065 If statement completed successfully?

   REVOKE GRANT OPTION FOR USAGE ON CHARACTER SET CS
         FROM CTS2 CASCADE;
-- PASS:7065 If grant option is revoked successfully?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS2';
-- PASS:7065 If statement completed successfully?

   SELECT TABLE_NAME, COLUMN_NAME, CHARACTER_SET_NAME,
         ORDINAL_POSITION
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLCH1';
-- PASS:7065 If TABLE_NAME = TEMP765A?
-- PASS:7065 If COLUMN_NAME = COLCH1?
-- PASS:7065 If CHARACTER_SET_NAME = CS?
-- PASS:7065 If ORDINAL_POSITION = 1?

   SELECT GRANTOR, GRANTEE, OBJECT_NAME, OBJECT_TYPE, 
         IS_GRANTABLE
         FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES 
         WHERE OBJECT_NAME = 'CS';
-- PASS:7065 If GRANTOR = CTS1?
-- PASS:7065 If GRANTEE = CTS2?
-- PASS:7065 If OBJECT_NAME = CS?
-- PASS:7065 If OBJECT_TYPE = CHARACTER SET?
-- PASS:7065 If IS_GRANTABLE = NO?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS3';
-- PASS:7065 If statement completed successfully?

   SELECT COUNT(*) 
         FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES 
         WHERE OBJECT_NAME = 'CS'
         AND (GRANTOR = 'CTS3' OR GRANTEE = 'CTS3');
-- PASS:7065 If COUNT = 0?

   SELECT COUNT(*) 
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLSTR1';
-- PASS:7065 If COUNT = 0?

   SELECT TABLE_NAME, COLUMN_NAME,
         ORDINAL_POSITION
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLNUM1';
-- PASS:7065 If TABLE_NAME = TEMP765B?
-- PASS:7065 If COLUMN_NAME = COLNUM1?
-- PASS:7065 If ORDINAL_POSITION = 1?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS1';
-- PASS:7065 If statement completed successfully?

   GRANT USAGE ON CHARACTER SET CS TO CTS2 
         WITH GRANT OPTION;
-- PASS:7065 If usage granted successfully?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS2';
-- PASS:7065 If statement completed successfully?

   GRANT USAGE ON CHARACTER SET CTS1.CS TO CTS3;
-- PASS:7065 If usage granted successfully?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS3';
-- PASS:7065 If statement completed successfully?

   CREATE TABLE TEMP765C 
         ( COLNIK1 CHAR(10) CHARACTER SET CTS1.CS,
           COLNUMBER1 DECIMAL(4));
-- PASS:7065 If table created successfully?

   COMMIT WORK;

   SELECT TABLE_NAME, COLUMN_NAME, CHARACTER_SET_NAME,
         ORDINAL_POSITION
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLNIK1';
-- PASS:7065 If TABLE_NAME = TEMP765C?
-- PASS:7065 If COLUMN_NAME = COLNIK1?
-- PASS:7065 If CHARACTER_SET_NAME = CS?
-- PASS:7065 If ORDINAL_POSITION = 1?

   SELECT TABLE_NAME, COLUMN_NAME,
         ORDINAL_POSITION
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLNUMBER1';
-- PASS:7065 If TABLE_NAME = TEMP765C?
-- PASS:7065 If COLUMN_NAME = COLNUMBER1?
-- PASS:7065 If ORDINAL_POSITION = 2?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS1';
-- PASS:7065 If statement completed successfully?

   REVOKE USAGE ON CHARACTER SET CS
         FROM CTS2 CASCADE;
-- PASS:7065 If usage revoked successfully?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS2';
-- PASS:7065 If statement completed successfully?

   SELECT COUNT(*) 
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLCH1';
-- PASS:7065 If COUNT = 0?

   SELECT TABLE_NAME, COLUMN_NAME,
         ORDINAL_POSITION
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLN';
-- PASS:7065 If TABLE_NAME = TEMP765A?
-- PASS:7065 If COLUMN_NAME = COLN?
-- PASS:7065 If ORDINAL_POSITION = 1?

   SELECT COUNT(*) 
         FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES 
         WHERE OBJECT_NAME = 'CS'
         AND (GRANTOR = 'CTS2' OR GRANTEE = 'CTS2');
-- PASS:7065 If COUNT = 0?

   COMMIT WORK;

   DROP TABLE TEMP765A CASCADE;
-- PASS:7065 If table dropped successfully?

   COMMIT WORK;

   SET SESSION AUTHORIZATION 'CTS3';
-- PASS:7065 If statement completed successfully?

   SELECT COUNT(*) 
         FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES 
         WHERE OBJECT_NAME = 'CS'
         AND (GRANTOR = 'CTS3' OR GRANTEE = 'CTS3');
-- PASS:7065 If COUNT = 0?

   SELECT COUNT(*) 
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLNIK1';
-- PASS:7065 If COUNT = 0?

   SELECT TABLE_NAME, COLUMN_NAME,
         ORDINAL_POSITION
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE COLUMN_NAME = 'COLNUMBER1';
-- PASS:7065 If TABLE_NAME = TEMP765C?
-- PASS:7065 If COLUMN_NAME = CP;MI,BER1?
-- PASS:7065 If ORDINAL_POSITION = 1?

   ROLLBACK WORK;

   DROP TABLE TEMP765B CASCADE;
-- PASS:7065 If table dropped successfully?

   COMMIT WORK;

   DROP TABLE TEMP765C CASCADE;
-- PASS:7065 If table dropped successfully?

   COMMIT WORK;

-- END TEST >>> 7065 <<< END TEST
-- *********************************************
-- *************************************************////END-OF-MODULE
