-- This is a restart file to be run after program xop723
--
-- run as authorization XOPEN1 

  CREATE TABLE AAA (A1 CHAR(2), A2 CHAR(2), A3 CHAR(2));
  CREATE TABLE BBB (B1 CHAR(2), B2 CHAR(2), B3 CHAR(2) NOT NULL);
  CREATE UNIQUE INDEX BBB_NDX ON BBB(B3);

  CREATE TABLE CCC (C1 CHAR(2), C2 CHAR(2), C3 CHAR(2));

-- ************* grant statements follow *************
   GRANT ALL PRIVILEGES ON XOPEN1.AAA TO XOPEN2;
   GRANT SELECT, UPDATE ON XOPEN1.AAA TO XOPEN2 WITH GRANT OPTION;
   GRANT INSERT, DELETE ON XOPEN1.BBB TO XOPEN2 WITH GRANT OPTION;
   GRANT SELECT ON XOPEN1.BBB TO XOPEN2 WITH GRANT OPTION;
   GRANT SELECT, INSERT ON XOPEN1.CCC TO XOPEN2;
-- ************* End of Schema *************
