DELETE FROM STATS 
WHERE MONTH = 7 
OR ID IN (SELECT ID FROM STATION 
WHERE LONG_W < 90);

DELETE FROM STATION WHERE LONG_W < 90;

COMMIT WORK;

SELECT * FROM STATION;

SELECT * FROM STATS;

SELECT * FROM METRIC_STATS;