-- ***************************************************************
-- ****** THIS FILE SHOULD BE RUN UNDER AUTHORIZATION ID HU ******
-- ***************************************************************

-- This is a nonconforming text file of interactive SQL commands.

-- This command file may be used to drop all the tables and views
--   for the authorization id  HU.

-- ************* Views *************

DROP VIEW TESTREPORT;
DROP VIEW CELSIUS_OBSERV;
DROP VIEW MULTI_YEAR_OBSERV;
DROP VIEW EXTREME_TEMPS;
DROP VIEW SET_TEST;
DROP VIEW DUP_COL;
DROP VIEW STAFFV1;
DROP VIEW STAFFV2;
DROP VIEW STAFFV2_VIEW;
DROP VIEW DOMAIN_VIEW;
DROP VIEW STAFF2;
DROP VIEW STAFF_WORKS_DESIGN;
DROP VIEW SUBSP;
DROP VIEW TEMP_SS;
DROP VIEW V_WORKS1;
DROP VIEW V_WORKS2;
DROP VIEW V_WORKS3;
DROP VIEW UPDATE_VIEW1;
DROP VIEW UPDATE_VIEW2;
DROP VIEW UPDATE_VIEW3;
DROP VIEW UPDATE_VIEW4;
DROP VIEW UPDATE_VIEW5;
DROP VIEW UPDATE_VIEW6;
DROP VIEW UPDATE_VIEW7;
DROP VIEW UPDATE_VIEW8;
DROP VIEW UPDATE_VIEW9;
DROP VIEW VSTAFF3;

-- ************* Tables ************* 

DROP TABLE BASE_TESTREPORT;
DROP TABLE ECCO;
DROP TABLE STAFF;
DROP TABLE PROJ;
DROP TABLE WORKS;
DROP TABLE FIPS1;
DROP TABLE STAFF1;
DROP TABLE PROJ1;
DROP TABLE WORKS1;
DROP TABLE STAFF3;
DROP TABLE STAFF4;
DROP TABLE LONGINT;
DROP TABLE TEMP_S;
DROP TABLE TMP;
DROP TABLE AA;
DROP TABLE BB ;
DROP TABLE CC ;
DROP TABLE DD ;
DROP TABLE EE ;
DROP TABLE FF ;
DROP TABLE GG ;
DROP TABLE HH ;
DROP TABLE II ;
DROP TABLE JJ ;
DROP TABLE KK ;
DROP TABLE LL ;
DROP TABLE MM ;
DROP TABLE MM2 ;
DROP TABLE NN ;
DROP TABLE OO ;
DROP TABLE PP ;
DROP TABLE QQ ;
DROP TABLE RR ;
DROP TABLE SS ;
DROP TABLE P1 ;
DROP TABLE P7 ;
DROP TABLE P12 ;
DROP TABLE P15 ;
DROP TABLE VTABLE ;
DROP TABLE UPUNIQ ;
DROP TABLE TEXT80 ;
DROP TABLE TEXT132;
DROP TABLE TEXT240;
DROP TABLE TEXT256;
DROP TABLE TEXT512;
DROP TABLE TEXT1024;
DROP TABLE T240;
DROP TABLE DEC15;
DROP TABLE FLO15;
DROP TABLE INT10;
DROP TABLE T100;
DROP TABLE T2000;
DROP TABLE T8;
DROP TABLE T118;
DROP TABLE T4;
DROP TABLE T12;
DROP TABLE NEXTKEY;
DROP TABLE SV;
DROP TABLE JJ_20;
DROP TABLE PP_15;
DROP TABLE PP_7;
DROP TABLE P15_15;
DROP TABLE P15_7;
DROP TABLE TEMP_OBSERV;
DROP TABLE TOKENS;
DROP TABLE WHICH_SCHEMA1;

COMMIT WORK;
